language: ruby
rvm:
  - 1.9.2
  # - 1.9.3
  # - 2.0.0
before_install:
  - gem update --system 1.8.25
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database tracks_test;'
script:
  - RAILS_ENV=test bundle exec rake db:test:prepare --trace
  - bundle exec rake spec --trace